[[fields]]
name = "id"
xpath = 21
index = "IdAutoIncrement"
list = true
weight = { min = 0, max = 0 }

[[fields]]
name = "id"
xpath = 21
index = "IdAutoIncrement"
list = true
weight = { min = 0, max = 0 }

[[fields]]
name = "year"
xpath = 2
index = "Text"
list = true
stemming = ""
weight = { min = 1, max = 50 }

[[fields]]
name = "cast"
xpath = 3
index = "Text"
list = true
stemming = "english"
weight = { min = 1, max = 75 }

[[fields]]
name = "genres"
xpath = 4
index = "Text"
list = true
stemming = ""
weight = { min = 1, max = 60 }

[[fields]]
name = "extract"
xpath = 5
index = "Text"
list = true
stemming = "english"
weight = { min = 1, max = 75 }

[[fields]]
name = "href"
xpath = 6
index = "None"
list = true
stemming = ""
weight = { min = 0, max = 0 }

[[fields]]
name = "thumbnail"
xpath = 7
index = "None"
list = true
stemming = ""
weight = { min = 0, max = 0 }

[[fields]]
name = "thumbnail_width"
xpath = 8
index = "None"
list = true
stemming = ""
weight = { min = 0, max = 0 }

[[fields]]
name = "thumbnail_height"
xpath = 9
index = "None"
list = true
stemming = ""
weight = { min = 0, max = 0 }
