//! Persistent, editable configuration for the synonym dictionary.
//!
//! On disk, next to the server's other files:
//!
//! ```text
//! <data root>/                       e.g. /tmp/corelamo
//!   CorelamoSettings.toml
//!   CorelamoSynonyms.syn             template; written from the built-in copy on first start
//!   databases/<db>/dictionary.syn    this database's dictionary, copied from the
//!                                    template when the database is created
//! ```
//!
//! Every database always has its own `dictionary.syn` and uses only that file.
//! Editing the template affects databases created afterwards, never existing
//! ones. Files round-trip losslessly: comments, blank lines and ordering
//! survive programmatic edits.

use std::collections::HashMap;
use std::fmt;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, MutexGuard, PoisonError, Weak};

use crate::syn::{
    parse_variant, DictionaryError, RomanConfig, SynonymDictionary, SynonymStore, Variant,
};

/// Seed for `CorelamoSynonyms.syn`: `default.syn` in the source tree,
/// generated by tools/build_default_dictionary.py and compiled into the
/// binary so a fresh data root gets a full dictionary on first start.
/// Anchored to this crate's Cargo.toml (core-query/ sits in the workspace root).
// crates/core-query/src/dictionary.rs
pub const DEFAULT_DICTIONARY: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../default.syn"));
pub const DEFAULT_LAYER_NAME: &str = "<built-in default>";

/// The template's file name in the data root, beside CorelamoSettings.toml.
pub const DEFAULT_FILE_NAME: &str = "CorelamoSynonyms.syn";

/// Each database's dictionary, inside that database's directory.
pub const DATABASE_FILE_NAME: &str = "dictionary.syn";

/// Written by `start_empty` so a blank dictionary explains itself.
pub const EMPTY_CUSTOM_DICTIONARY: &str = "\
# Synonym dictionary for this database.
# It is currently empty: no synonyms are expanded.
";

static TMP_COUNTER: AtomicU64 = AtomicU64::new(0);
impl From<ConfigError> for core_protocol::errors::CorelamoError {
    fn from(err: ConfigError) -> Self {
        use core_protocol::errors::CorelamoError;
        match err {
            ConfigError::Io { .. } => CorelamoError::Internal(err.to_string()),
            _ => CorelamoError::InvalidData(err.to_string()),
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Section {
    Roman,
    Synonyms,
    Acronyms,
    Formulas,
}

impl Section {
    pub fn name(self) -> &'static str {
        match self {
            Section::Roman => "roman",
            Section::Synonyms => "synonyms",
            Section::Acronyms => "acronyms",
            Section::Formulas => "formulas",
        }
    }

    fn from_name(name: &str) -> Option<Self> {
        match name.trim().to_ascii_lowercase().as_str() {
            "roman" => Some(Section::Roman),
            "synonyms" => Some(Section::Synonyms),
            "acronyms" => Some(Section::Acronyms),
            "formulas" => Some(Section::Formulas),
            _ => None,
        }
    }

    pub fn holds_groups(self) -> bool {
        matches!(self, Section::Synonyms | Section::Acronyms | Section::Formulas)
    }
}

#[derive(Debug)]
pub enum ConfigError {
    Io { path: PathBuf, source: io::Error },
    Syntax { source_name: String, line: Option<usize>, message: String },
    Dictionary { source_name: String, line: Option<usize>, source: DictionaryError },
    Invalid { message: String },
    Conflict { path: PathBuf },
    NoPath { source_name: String },
}

fn location(source_name: &str, line: Option<usize>) -> String {
    match line {
        Some(line) => format!("{source_name}:{line}"),
        None => source_name.to_owned(),
    }
}

impl fmt::Display for ConfigError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => write!(f, "{}: {source}", path.display()),
            Self::Syntax { source_name, line, message } => {
                write!(f, "{}: {message}", location(source_name, *line))
            }
            Self::Dictionary { source_name, line, source } => {
                write!(f, "{}: {source}", location(source_name, *line))
            }
            Self::Invalid { message } => write!(f, "invalid configuration: {message}"),
            Self::Conflict { path } => write!(
                f,
                "{} changed on disk since it was loaded; reload before editing",
                path.display()
            ),
            Self::NoPath { source_name } => {
                write!(f, "{source_name} has no file path; use save_as")
            }
        }
    }
}

impl std::error::Error for ConfigError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Dictionary { source, .. } => Some(source),
            _ => None,
        }
    }
}

enum LineError {
    Syntax(String),
    Dictionary(DictionaryError),
}

impl LineError {
    fn at(self, source_name: &str, line: Option<usize>) -> ConfigError {
        let source_name = source_name.to_owned();
        match self {
            LineError::Syntax(message) => ConfigError::Syntax { source_name, line, message },
            LineError::Dictionary(source) => ConfigError::Dictionary { source_name, line, source },
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum SettingValue {
    Bool(bool),
    Number(u16),
    List(Vec<String>),
}

#[derive(Debug, Clone)]
struct Setting {
    key: String,
    value: SettingValue,
}

#[derive(Debug, Clone)]
struct GroupEntry {
    specs: Vec<String>,
    variants: Vec<Variant>,
}

#[derive(Debug, Clone)]
enum Entry {
    Blank,
    Comment,
    Header,
    Setting(Setting),
    Group(GroupEntry),
}

#[derive(Debug, Clone)]
struct Line {
    raw: String,
    section: Section,
    entry: Entry,
}

fn strip_comment(raw: &str) -> &str {
    raw.find('#').map_or(raw, |pos| &raw[..pos])
}

const FORBIDDEN_CHARS: &[char] = &['|', '#', '\n', '\r'];

fn check_spec(spec: &str) -> Result<(), LineError> {
    let trimmed = spec.trim_start();
    if spec.contains(FORBIDDEN_CHARS) || trimmed.starts_with(&['-', '['][..]) {
        return Err(LineError::Syntax(format!(
            "variant {spec:?} may not contain `|`, `#` or line breaks, or start with `-` or `[`"
        )));
    }
    Ok(())
}

fn parse_group<'a>(specs: impl IntoIterator<Item = &'a str>) -> Result<GroupEntry, LineError> {
    let mut group = GroupEntry { specs: Vec::new(), variants: Vec::new() };
    for spec in specs.into_iter().map(str::trim).filter(|spec| !spec.is_empty()) {
        let variant = parse_variant(spec).map_err(LineError::Dictionary)?;
        if !group.variants.contains(&variant) {
            group.specs.push(spec.to_owned());
            group.variants.push(variant);
        }
    }
    if group.variants.len() < 2 {
        return Err(LineError::Dictionary(DictionaryError::GroupTooSmall {
            variants: group.variants.len(),
        }));
    }
    Ok(group)
}

fn parse_number(
    key: &str,
    value: &str,
    range: std::ops::RangeInclusive<u16>,
) -> Result<u16, LineError> {
    value.parse::<u16>().ok().filter(|n| range.contains(n)).ok_or_else(|| {
        LineError::Syntax(format!(
            "`{key}` must be an integer in {}..={}, got {value:?}",
            range.start(),
            range.end()
        ))
    })
}

fn validate_setting(section: Section, key: &str, value: &str) -> Result<SettingValue, LineError> {
    match (section, key) {
        (Section::Roman, "enabled")
        | (Section::Roman, "arabic_to_roman") => match value.to_ascii_lowercase().as_str() {
            "true" => Ok(SettingValue::Bool(true)),
            "false" => Ok(SettingValue::Bool(false)),
            _ => Err(LineError::Syntax(format!(
                "`{key}` must be true or false, got {value:?}"
            ))),
        },
        (Section::Roman, "min_value") | (Section::Roman, "max_value") => {
            parse_number(key, value, 1..=3999).map(SettingValue::Number)
        }
        (Section::Roman, "min_len") => parse_number(key, value, 1..=15).map(SettingValue::Number),
        (Section::Roman, "denylist") => {
            let mut items = Vec::new();
            for item in value.split(',').map(str::trim).filter(|item| !item.is_empty()) {
                let upper = item.to_ascii_uppercase();
                if !upper.chars().all(|c| "IVXLCDM".contains(c)) {
                    return Err(LineError::Syntax(format!(
                        "denylist entry {item:?} is not made of Roman numeral letters"
                    )));
                }
                items.push(upper);
            }
            Ok(SettingValue::List(items))
        }
        _ => Err(LineError::Syntax(format!(
            "unknown setting `{key}` in [{}]",
            section.name()
        ))),
    }
}

fn parse_line(raw: &str, current: Section) -> Result<(Section, Entry), LineError> {
    let content = strip_comment(raw).trim();
    if content.is_empty() {
        let entry = if raw.trim().is_empty() { Entry::Blank } else { Entry::Comment };
        return Ok((current, entry));
    }
    if let Some(name) = content.strip_prefix('[').and_then(|rest| rest.strip_suffix(']')) {
        let section = Section::from_name(name).ok_or_else(|| {
            LineError::Syntax(format!(
                "unknown section [{name}]; expected roman, synonyms, acronyms or formulas"
            ))
        })?;
        return Ok((section, Entry::Header));
    }
    if current.holds_groups() {
        if content.starts_with('-') {
            return Err(LineError::Syntax(
                "lines starting with `-` are not supported; this file is the whole dictionary, \
                 so delete the entry instead"
                    .to_owned(),
            ));
        }
        return parse_group(content.split('|')).map(|group| (current, Entry::Group(group)));
    }
    let eq = content.find('=').ok_or_else(|| {
        LineError::Syntax(format!(
            "expected `key = value` in [{}]; synonym groups belong in [synonyms], [acronyms] or [formulas]",
            current.name()
        ))
    })?;
    let key = content[..eq].trim();
    if key.ends_with('+') || key.ends_with('-') {
        return Err(LineError::Syntax(
            "`+=` and `-=` are not supported; write the full value with `=`".to_owned(),
        ));
    }
    let value = validate_setting(current, key, content[eq + 1..].trim())?;
    Ok((current, Entry::Setting(Setting { key: key.to_owned(), value })))
}

fn fingerprint(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0xcbf2_9ce4_8422_2325_u64, |hash, &byte| {
        (hash ^ u64::from(byte)).wrapping_mul(0x0000_0100_0000_01b3)
    })
}

fn parent_dir(path: &Path) -> PathBuf {
    match path.parent() {
        Some(parent) if !parent.as_os_str().is_empty() => parent.to_path_buf(),
        _ => PathBuf::from("."),
    }
}

fn write_atomic(path: &Path, bytes: &[u8]) -> io::Result<()> {
    let dir = parent_dir(path);
    fs::create_dir_all(&dir)?;
    let file_name = path
        .file_name()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "path has no file name"))?;
    let tmp = dir.join(format!(
        ".{}.{}.{}.tmp",
        file_name.to_string_lossy(),
        std::process::id(),
        TMP_COUNTER.fetch_add(1, Ordering::Relaxed)
    ));
    let result = (|| {
        let mut file = OpenOptions::new().write(true).create_new(true).open(&tmp)?;
        file.write_all(bytes)?;
        file.sync_all()?;
        fs::rename(&tmp, path)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&tmp);
    }
    result?;
    sync_dir(&dir)
}

#[cfg(unix)]
fn sync_dir(dir: &Path) -> io::Result<()> {
    File::open(dir)?.sync_all()
}

#[cfg(not(unix))]
fn sync_dir(_dir: &Path) -> io::Result<()> {
    Ok(())
}

/// Fails with `Conflict` unless the file on disk is exactly what was loaded
/// (`None` = the file was absent and must still be absent).
fn check_unchanged(path: &Path, expected: Option<u64>) -> Result<(), ConfigError> {
    let on_disk = match fs::read(path) {
        Ok(bytes) => Some(fingerprint(&bytes)),
        Err(err) if err.kind() == io::ErrorKind::NotFound => None,
        Err(source) => return Err(ConfigError::Io { path: path.to_path_buf(), source }),
    };
    if on_disk == expected {
        Ok(())
    } else {
        Err(ConfigError::Conflict { path: path.to_path_buf() })
    }
}

/// One dictionary file, held as its original lines plus their parsed meaning.
#[derive(Debug, Clone)]
pub struct ConfigDocument {
    name: String,
    lines: Vec<Line>,
    path: Option<PathBuf>,
    disk_fingerprint: Option<u64>,
}

impl ConfigDocument {
    pub fn empty(name: impl Into<String>) -> Self {
        Self { name: name.into(), lines: Vec::new(), path: None, disk_fingerprint: None }
    }

    pub fn parse(name: impl Into<String>, text: &str) -> Result<Self, ConfigError> {
        let name = name.into();
        let mut section = Section::Synonyms;
        let mut lines = Vec::new();
        let mut seen_settings: HashMap<(Section, String), usize> = HashMap::new();
        for (index, raw) in text.lines().enumerate() {
            let line_number = index + 1;
            let (next, entry) =
                parse_line(raw, section).map_err(|err| err.at(&name, Some(line_number)))?;
            section = next;
            if let Entry::Setting(setting) = &entry {
                if let Some(first) =
                    seen_settings.insert((section, setting.key.clone()), line_number)
                {
                    return Err(ConfigError::Syntax {
                        source_name: name,
                        line: Some(line_number),
                        message: format!(
                            "`{}` is already set on line {first}; keep only one",
                            setting.key
                        ),
                    });
                }
            }
            lines.push(Line { raw: raw.to_owned(), section, entry });
        }
        Ok(Self { name, lines, path: None, disk_fingerprint: None })
    }

    pub fn builtin_default() -> Result<Self, ConfigError> {
        Self::parse(DEFAULT_LAYER_NAME, DEFAULT_DICTIONARY)
    }

    /// A missing file loads as an empty document bound to `path` with
    /// `exists_on_disk() == false`.
    pub fn load(path: impl AsRef<Path>) -> Result<Self, ConfigError> {
        let path = path.as_ref();
        match fs::read(path) {
            Ok(bytes) => {
                let text = String::from_utf8(bytes).map_err(|err| ConfigError::Io {
                    path: path.to_path_buf(),
                    source: io::Error::new(io::ErrorKind::InvalidData, err),
                })?;
                let mut doc = Self::parse(path.display().to_string(), &text)?;
                doc.path = Some(path.to_path_buf());
                doc.disk_fingerprint = Some(fingerprint(text.as_bytes()));
                Ok(doc)
            }
            Err(err) if err.kind() == io::ErrorKind::NotFound => {
                let mut doc = Self::empty(path.display().to_string());
                doc.path = Some(path.to_path_buf());
                Ok(doc)
            }
            Err(source) => Err(ConfigError::Io { path: path.to_path_buf(), source }),
        }
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn path(&self) -> Option<&Path> {
        self.path.as_deref()
    }

    /// True once this document has been loaded from, or saved to, a file.
    pub fn exists_on_disk(&self) -> bool {
        self.disk_fingerprint.is_some()
    }

    fn require_path(&self) -> Result<PathBuf, ConfigError> {
        self.path
            .clone()
            .ok_or_else(|| ConfigError::NoPath { source_name: self.name.clone() })
    }

    /// Takes over another document's file identity (name, path, last-seen state).
    fn bound_to(mut self, target: &ConfigDocument) -> Self {
        self.name = target.name.clone();
        self.path = target.path.clone();
        self.disk_fingerprint = target.disk_fingerprint;
        self
    }

    pub fn render(&self) -> String {
        let mut out = String::with_capacity(self.lines.iter().map(|l| l.raw.len() + 1).sum());
        for line in &self.lines {
            out.push_str(&line.raw);
            out.push('\n');
        }
        out
    }

    /// Atomic save that refuses to overwrite changes made on disk since load.
    pub fn save(&mut self) -> Result<(), ConfigError> {
        let path = self.require_path()?;
        check_unchanged(&path, self.disk_fingerprint)?;
        self.write_to(&path)
    }

    /// Atomic save to `path`, overwriting whatever is there.
    pub fn save_as(&mut self, path: impl AsRef<Path>) -> Result<(), ConfigError> {
        let path = path.as_ref().to_path_buf();
        self.write_to(&path)?;
        self.name = path.display().to_string();
        self.path = Some(path);
        Ok(())
    }

    fn write_to(&mut self, path: &Path) -> Result<(), ConfigError> {
        let text = self.render();
        write_atomic(path, text.as_bytes())
            .map_err(|source| ConfigError::Io { path: path.to_path_buf(), source })?;
        self.disk_fingerprint = Some(fingerprint(text.as_bytes()));
        Ok(())
    }

    pub fn add_group(&mut self, section: Section, specs: &[&str]) -> Result<(), ConfigError> {
        if !section.holds_groups() {
            return Err(ConfigError::Invalid {
                message: format!("[{}] cannot hold synonym groups", section.name()),
            });
        }
        for spec in specs {
            check_spec(spec).map_err(|err| err.at(&self.name, None))?;
        }
        let group = parse_group(specs.iter().copied()).map_err(|err| err.at(&self.name, None))?;
        let raw = group.specs.join(" | ");
        self.insert_in_section(section, raw, Entry::Group(group));
        Ok(())
    }

    /// Removes a word from every group in this file; groups left with fewer
    /// than two words are deleted. Returns the number of lines changed.
    pub fn remove_variant(&mut self, spec: &str) -> Result<usize, ConfigError> {
        let target = parse_variant(spec)
            .map_err(|source| ConfigError::Dictionary {
                source_name: self.name.clone(),
                line: None,
                source,
            })?
            .key();
        let mut changed = 0;
        let mut kept = Vec::with_capacity(self.lines.len());
        for mut line in std::mem::take(&mut self.lines) {
            if let Entry::Group(group) = &mut line.entry {
                let before = group.variants.len();
                let (specs, variants): (Vec<String>, Vec<Variant>) = group
                    .specs
                    .drain(..)
                    .zip(group.variants.drain(..))
                    .filter(|(_, variant)| variant.key() != target)
                    .unzip();
                group.specs = specs;
                group.variants = variants;
                if group.variants.len() != before {
                    changed += 1;
                    if group.variants.len() < 2 {
                        continue;
                    }
                    line.raw = group.specs.join(" | ");
                }
            }
            kept.push(line);
        }
        self.lines = kept;
        Ok(changed)
    }

    /// Sets a key, replacing its existing line in place or adding it.
    pub fn set_setting(&mut self, section: Section, key: &str, value: &str) -> Result<(), ConfigError> {
        if value.contains(FORBIDDEN_CHARS) {
            return Err(ConfigError::Invalid {
                message: format!("setting value {value:?} may not contain `|`, `#` or line breaks"),
            });
        }
        let parsed = validate_setting(section, key, value.trim())
            .map_err(|err| err.at(&self.name, None))?;
        let raw = format!("{key} = {}", value.trim());
        let entry = Entry::Setting(Setting { key: key.to_owned(), value: parsed });
        let existing = self.lines.iter().position(|l| {
            l.section == section && matches!(&l.entry, Entry::Setting(s) if s.key == key)
        });
        match existing {
            Some(index) => self.lines[index] = Line { raw, section, entry },
            None => self.insert_in_section(section, raw, entry),
        }
        Ok(())
    }

    fn insert_in_section(&mut self, section: Section, raw: String, entry: Entry) {
        let line = Line { raw, section, entry };
        let anchor = self
            .lines
            .iter()
            .rposition(|l| l.section == section && !matches!(l.entry, Entry::Blank));
        if let Some(index) = anchor {
            self.lines.insert(index + 1, line);
            return;
        }
        if let Some(last) = self.lines.last() {
            if !matches!(last.entry, Entry::Blank) {
                let previous_section = last.section;
                self.lines.push(Line {
                    raw: String::new(),
                    section: previous_section,
                    entry: Entry::Blank,
                });
            }
        }
        self.lines.push(Line {
            raw: format!("[{}]", section.name()),
            section,
            entry: Entry::Header,
        });
        self.lines.push(line);
    }
}

fn apply_setting(setting: &Setting, section: Section, roman: &mut RomanConfig) {
    match (section, setting.key.as_str(), &setting.value) {
        (Section::Roman, "enabled", SettingValue::Bool(b)) => roman.enabled = *b,
        (Section::Roman, "arabic_to_roman", SettingValue::Bool(b)) => roman.arabic_to_roman = *b,
        (Section::Roman, "min_value", SettingValue::Number(n)) => roman.min_value = *n,
        (Section::Roman, "max_value", SettingValue::Number(n)) => roman.max_value = *n,
        (Section::Roman, "min_len", SettingValue::Number(n)) => roman.min_len = usize::from(*n),
        (Section::Roman, "denylist", SettingValue::List(items)) => {
            roman.denylist = items.iter().cloned().collect()
        }
        // Every other combination is rejected by validate_setting at parse time.
        _ => {}
    }
}

/// Compiles one complete dictionary file. Settings it omits take the
/// compiled-in defaults, which match `default.syn` (enforced by a test).
pub fn compile(doc: &ConfigDocument) -> Result<SynonymDictionary, ConfigError> {
    let mut roman = RomanConfig::default();
    let mut builder = SynonymDictionary::builder();
    for line in &doc.lines {
        match &line.entry {
            Entry::Setting(setting) => {
                apply_setting(setting, line.section, &mut roman)
            }
            Entry::Group(group) => {
                builder.add_group(group.variants.clone()).map_err(|source| {
                    ConfigError::Dictionary { source_name: doc.name.clone(), line: None, source }
                })?;
            }
            Entry::Blank | Entry::Comment | Entry::Header => {}
        }
    }
    if roman.min_value > roman.max_value {
        return Err(ConfigError::Invalid {
            message: format!(
                "{}: roman min_value ({}) exceeds max_value ({})",
                doc.name, roman.min_value, roman.max_value
            ),
        });
    }
    builder.roman(roman);
    Ok(builder.build())
}

fn lock<T>(mutex: &Mutex<T>) -> MutexGuard<'_, T> {
    mutex.lock().unwrap_or_else(PoisonError::into_inner)
}

/// Loads `path`, first writing the built-in dictionary there if it is missing.
fn load_or_seed(path: &Path) -> Result<ConfigDocument, ConfigError> {
    let doc = ConfigDocument::load(path)?;
    if doc.exists_on_disk() {
        return Ok(doc);
    }
    let mut seeded = ConfigDocument::builtin_default()?.bound_to(&doc);
    seeded.save()?;
    Ok(seeded)
}

/// Shares one compiled dictionary between databases whose files are
/// identical, which is every database whose copy hasn't been edited. A full
/// English dictionary is tens of MB compiled; without this each database
/// would hold its own copy. Entries die with their last user.
#[derive(Debug, Default)]
struct CompiledCache {
    entries: Mutex<HashMap<(u64, usize), Weak<SynonymDictionary>>>,
}

impl CompiledCache {
    fn get_or_compile(&self, doc: &ConfigDocument) -> Result<Arc<SynonymDictionary>, ConfigError> {
        let text = doc.render();
        let key = (fingerprint(text.as_bytes()), text.len());
        let mut entries = lock(&self.entries);
        if let Some(shared) = entries.get(&key).and_then(Weak::upgrade) {
            return Ok(shared);
        }
        let compiled = Arc::new(compile(doc)?);
        entries.retain(|_, weak| weak.strong_count() > 0);
        entries.insert(key, Arc::downgrade(&compiled));
        Ok(compiled)
    }
}

/// Entry point for the server: knows the template next to
/// CorelamoSettings.toml and opens each database's dictionary.
#[derive(Debug)]
pub struct SynonymRegistry {
    template_path: PathBuf,
    //serializes template edits against copies taken from it
    template_lock: Mutex<()>,
    cache: Arc<CompiledCache>,
}

impl SynonymRegistry {
    /// `data_root` is the directory holding CorelamoSettings.toml. Writes the
    /// template from the built-in copy if it is missing, and fails (with file
    /// and line) if an existing template doesn't parse, like a broken
    /// settings file would.
    pub fn open(data_root: impl AsRef<Path>) -> Result<Self, ConfigError> {
        let template_path = data_root.as_ref().join(DEFAULT_FILE_NAME);
        let template = load_or_seed(&template_path)?;
        compile(&template)?;
        Ok(Self { template_path, template_lock: Mutex::new(()), cache: Arc::default() })
    }

    pub fn template_path(&self) -> &Path {
        &self.template_path
    }

    /// The template as it is on disk right now (re-seeded if deleted).
    fn read_template(&self) -> Result<ConfigDocument, ConfigError> {
        let template = load_or_seed(&self.template_path)?;
        compile(&template)?;
        Ok(template)
    }

    pub fn template_text(&self) -> Result<String, ConfigError> {
        let _guard = lock(&self.template_lock);
        Ok(self.read_template()?.render())
    }

    /// Opens `<database_dir>/dictionary.syn`. If the database has none (it is
    /// being created, or predates dictionaries), the current template is
    /// copied in first. An existing file is never touched.
    pub fn open_database(&self, database_dir: impl AsRef<Path>) -> Result<SynonymManager, ConfigError> {
        let path = database_dir.as_ref().join(DATABASE_FILE_NAME);
        let mut file = ConfigDocument::load(&path)?;
        if !file.exists_on_disk() {
            file = self.copy_template_to(&file)?;
        }
        let dictionary = self.cache.get_or_compile(&file)?;
        Ok(SynonymManager {
            template_path: self.template_path.clone(),
            cache: Arc::clone(&self.cache),
            file: Mutex::new(file),
            store: SynonymStore::from_arc(dictionary),
        })
    }

    /// Writes the template into `target`'s file. `target` must not exist yet.
    fn copy_template_to(&self, target: &ConfigDocument) -> Result<ConfigDocument, ConfigError> {
        let _guard = lock(&self.template_lock);
        let mut copy = self.read_template()?.bound_to(target);
        copy.save()?;
        Ok(copy)
    }

    /// Edits the template. Existing databases keep their own copies.
    pub fn edit_template<F>(&self, edit: F) -> Result<(), ConfigError>
    where
        F: FnOnce(&mut ConfigDocument) -> Result<(), ConfigError>,
    {
        let _guard = lock(&self.template_lock);
        let mut draft = self.read_template()?;
        edit(&mut draft)?;
        compile(&draft)?;
        draft.save()
    }

    pub fn replace_template_text(&self, text: &str) -> Result<(), ConfigError> {
        self.edit_template(|draft| {
            let parsed = ConfigDocument::parse(draft.name.clone(), text)?;
            *draft = parsed.bound_to(draft);
            Ok(())
        })
    }

    /// Overwrites the template with the dictionary compiled into this binary
    /// (e.g. after upgrading to a build with a newer default.syn).
    pub fn restore_builtin_template(&self) -> Result<(), ConfigError> {
        self.replace_template_text(DEFAULT_DICTIONARY)
    }
}

/// One database's dictionary: always its own `dictionary.syn`.
#[derive(Debug)]
pub struct SynonymManager {
    template_path: PathBuf,
    cache: Arc<CompiledCache>,
    file: Mutex<ConfigDocument>,
    store: SynonymStore,
}

impl SynonymManager {
    /// Take once per request and share it with every shard.
    pub fn snapshot(&self) -> Arc<SynonymDictionary> {
        self.store.snapshot()
    }

    pub fn path(&self) -> Option<PathBuf> {
        lock(&self.file).path().map(Path::to_path_buf)
    }

    pub fn config_text(&self) -> String {
        lock(&self.file).render()
    }

    /// Re-reads the file after a manual edit or a restore. A deleted file is
    /// copied from the template again. On any error the live dictionary stays.
    pub fn reload(&self) -> Result<(), ConfigError> {
        let mut file = lock(&self.file);
        let mut fresh = ConfigDocument::load(file.require_path()?)?;
        if !fresh.exists_on_disk() {
            let template = load_or_seed(&self.template_path)?;
            let mut copy = template.bound_to(&fresh);
            copy.save()?;
            fresh = copy;
        }
        let dictionary = self.cache.get_or_compile(&fresh)?;
        self.store.replace_arc(dictionary);
        *file = fresh;
        Ok(())
    }

    /// Transactional edit: validated and saved atomically before it goes live.
    pub fn edit<F>(&self, edit: F) -> Result<(), ConfigError>
    where
        F: FnOnce(&mut ConfigDocument) -> Result<(), ConfigError>,
    {
        let mut file = lock(&self.file);
        let mut draft = file.clone();
        edit(&mut draft)?;
        self.commit(&mut file, draft)
    }

    /// Replaces this database's dictionary with the given file contents.
    pub fn replace_text(&self, text: &str) -> Result<(), ConfigError> {
        let mut file = lock(&self.file);
        let draft = ConfigDocument::parse(file.name.clone(), text)?;
        self.commit(&mut file, draft)
    }

    /// Gives this database an empty dictionary (no synonyms at all).
    pub fn start_empty(&self) -> Result<(), ConfigError> {
        self.replace_text(EMPTY_CUSTOM_DICTIONARY)
    }

    /// Overwrites this database's dictionary with the current template.
    pub fn reset_to_template(&self) -> Result<(), ConfigError> {
        let template = load_or_seed(&self.template_path)?;
        let mut file = lock(&self.file);
        self.commit(&mut file, template)
    }

    fn commit(&self, file: &mut ConfigDocument, draft: ConfigDocument) -> Result<(), ConfigError> {
        let mut draft = draft.bound_to(file);
        let dictionary = self.cache.get_or_compile(&draft)?;
        draft.save()?;
        self.store.replace_arc(dictionary);
        *file = draft;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::syn::QueryNode;

    fn term(s: &str) -> QueryNode {
        QueryNode::Term(s.to_owned())
    }

    fn phrase(words: &[&str]) -> QueryNode {
        QueryNode::Phrase(words.iter().map(|w| (*w).to_owned()).collect())
    }

    fn exact(words: &[&str]) -> QueryNode {
        QueryNode::Exact(words.iter().map(|w| (*w).to_owned()).collect())
    }

    fn any(nodes: Vec<QueryNode>) -> Vec<QueryNode> {
        vec![QueryNode::AnyOf(nodes)]
    }

    fn temp_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "synonym-config-{tag}-{}-{}",
            std::process::id(),
            TMP_COUNTER.fetch_add(1, Ordering::Relaxed)
        ));
        // PIDs repeat across runs in containers; never inherit a stale file.
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    const SMALL_TEMPLATE: &str = "[acronyms]\nCaP | calcium phosphate\n";

    /// Data root with a small template, so tests don't depend on the full default.
    fn registry(tag: &str) -> (PathBuf, SynonymRegistry) {
        let root = temp_dir(tag);
        fs::write(root.join(DEFAULT_FILE_NAME), SMALL_TEMPLATE).unwrap();
        let registry = SynonymRegistry::open(&root).unwrap();
        (root, registry)
    }

    fn cap_expansion() -> Vec<QueryNode> {
        any(vec![exact(&["CaP"]), phrase(&["calcium", "phosphate"])])
    }

    #[test]
    fn builtin_default_compiles() {
        let dict = compile(&ConfigDocument::builtin_default().unwrap()).unwrap();
        assert_eq!(dict.expand_query("H2O"), any(vec![exact(&["H2O"]), term("water")]));
        assert_eq!(dict.expand_query("it"), vec![term("it")]);
    }

    #[test]
    fn omitted_settings_match_default_file() {
        let from_default = compile(&ConfigDocument::builtin_default().unwrap()).unwrap();
        let from_empty = compile(&ConfigDocument::empty("custom")).unwrap();
        for query in ["I", "II", "IV", "MIX", "XL", "MMXXVI", "1", "2", "40", "2026", "C"] {
            assert_eq!(
                from_default.expand_number(query),
                from_empty.expand_number(query),
                "query {query}"
            );
        }
    }

    #[test]
    fn round_trip_is_lossless() {
        let text = "# my dictionary\n[acronyms]\nCaP | calcium phosphate   # bone mineral\n\n[roman]\nmin_value = 3\n";
        assert_eq!(ConfigDocument::parse("t", text).unwrap().render(), text);
    }

    #[test]
    fn rejects_layering_syntax_and_duplicates_with_line_numbers() {
        let err = ConfigDocument::parse("db", "[acronyms]\nHA | hydroxyapatite\n- IT\n").unwrap_err();
        assert!(matches!(err, ConfigError::Syntax { line: Some(3), .. }), "{err}");
        let err = ConfigDocument::parse("db", "[roman]\ndenylist += IV\n").unwrap_err();
        assert!(matches!(err, ConfigError::Syntax { line: Some(2), .. }), "{err}");
        let err = ConfigDocument::parse("db", "[roman]\nmin_value = 2\nmin_value = 3\n").unwrap_err();
        assert!(matches!(err, ConfigError::Syntax { line: Some(3), .. }), "{err}");
        let err = ConfigDocument::parse("db", "[romans]\n").unwrap_err();
        assert!(matches!(err, ConfigError::Syntax { line: Some(1), .. }), "{err}");
    }

    #[test]
    fn programmatic_edits_preserve_layout() {
        let mut doc = ConfigDocument::parse(
            "t",
            "[roman]\nmin_value = 2\nmax_value = 100\n\n[synonyms]\nbig | large | huge\nfast | quick\n",
        )
        .unwrap();
        doc.set_setting(Section::Roman, "min_value", "3").unwrap();
        assert_eq!(doc.remove_variant("quick").unwrap(), 1);
        assert_eq!(doc.remove_variant("huge").unwrap(), 1);
        doc.add_group(Section::Synonyms, &["small", "little"]).unwrap();
        doc.add_group(Section::Acronyms, &["HA", "hydroxyapatite"]).unwrap();
        assert_eq!(
            doc.render(),
            "[roman]\nmin_value = 3\nmax_value = 100\n\n[synonyms]\nbig | large\nsmall | little\n\n[acronyms]\nHA | hydroxyapatite\n"
        );
        assert!(doc.add_group(Section::Synonyms, &["a | b", "c"]).is_err());
    }


    #[test]
    fn first_start_writes_builtin_template() {
        let root = temp_dir("seed");
        let registry = SynonymRegistry::open(&root).unwrap();
        let expected = ConfigDocument::builtin_default().unwrap().render();
        assert_eq!(fs::read_to_string(root.join(DEFAULT_FILE_NAME)).unwrap(), expected);
        assert_eq!(registry.template_text().unwrap(), expected);
    }

    #[test]
    fn existing_template_is_never_overwritten_on_start() {
        let (root, _registry) = registry("keep");
        let _again = SynonymRegistry::open(&root).unwrap();
        assert_eq!(fs::read_to_string(root.join(DEFAULT_FILE_NAME)).unwrap(), SMALL_TEMPLATE);
    }

    #[test]
    fn broken_template_fails_with_line_number() {
        let root = temp_dir("broken");
        fs::write(root.join(DEFAULT_FILE_NAME), "[acronyms]\nHA | hydroxyapatite\nPVP\n").unwrap();
        let err = SynonymRegistry::open(&root).unwrap_err();
        assert!(matches!(err, ConfigError::Dictionary { line: Some(3), .. }), "{err}");
    }

    #[test]
    fn new_database_gets_a_copy_of_the_template() {
        let (root, registry) = registry("copy");
        let db_dir = root.join("databases").join("movies");
        let db = registry.open_database(&db_dir).unwrap();
        assert_eq!(fs::read_to_string(db_dir.join(DATABASE_FILE_NAME)).unwrap(), SMALL_TEMPLATE);
        assert_eq!(db.snapshot().expand_query("CaP"), cap_expansion());
    }

    #[test]
    fn template_edits_only_reach_databases_created_afterwards() {
        let (root, registry) = registry("later");
        let old_db = registry.open_database(root.join("databases").join("old")).unwrap();

        registry
            .edit_template(|doc| doc.add_group(Section::Acronyms, &["HA", "hydroxyapatite"]))
            .unwrap();
        let new_db = registry.open_database(root.join("databases").join("new")).unwrap();

        assert_eq!(old_db.snapshot().expand_query("HA"), vec![term("ha")]);
        assert_eq!(
            new_db.snapshot().expand_query("HA"),
            any(vec![exact(&["HA"]), term("hydroxyapatite")])
        );
        //reopening the old database keeps its own file
        let reopened = registry.open_database(root.join("databases").join("old")).unwrap();
        assert_eq!(reopened.snapshot().expand_query("HA"), vec![term("ha")]);
    }

    #[test]
    fn hand_edited_template_is_copied_as_it_is_on_disk() {
        let (root, registry) = registry("hand");
        fs::write(root.join(DEFAULT_FILE_NAME), "[acronyms]\nPVP | polyvinylpyrrolidone\n").unwrap();
        let db = registry.open_database(root.join("databases").join("db")).unwrap();
        assert_eq!(
            db.snapshot().expand_query("PVP"),
            any(vec![exact(&["PVP"]), term("polyvinylpyrrolidone")])
        );

        //a template broken after startup blocks creation and leaves no half-made file
        fs::write(root.join(DEFAULT_FILE_NAME), "[acronyms]\nPVP\n").unwrap();
        let db_dir = root.join("databases").join("blocked");
        assert!(registry.open_database(&db_dir).is_err());
        assert!(!db_dir.join(DATABASE_FILE_NAME).exists());
    }

    #[test]
    fn identical_copies_share_one_compiled_dictionary() {
        let (root, registry) = registry("shared");
        let a = registry.open_database(root.join("databases").join("a")).unwrap();
        let b = registry.open_database(root.join("databases").join("b")).unwrap();
        assert!(Arc::ptr_eq(&a.snapshot(), &b.snapshot()));

        b.edit(|doc| doc.add_group(Section::Acronyms, &["HA", "hydroxyapatite"])).unwrap();
        assert!(!Arc::ptr_eq(&a.snapshot(), &b.snapshot()));
        assert_eq!(a.snapshot().expand_query("HA"), vec![term("ha")]);

        b.reset_to_template().unwrap();
        assert!(Arc::ptr_eq(&a.snapshot(), &b.snapshot()));
    }

    #[test]
    fn database_edits_empty_and_reset() {
        let (root, registry) = registry("edits");
        let db_dir = root.join("databases").join("db");
        let db = registry.open_database(&db_dir).unwrap();
        let path = db_dir.join(DATABASE_FILE_NAME);

        db.edit(|doc| doc.add_group(Section::Acronyms, &["HA", "hydroxyapatite"])).unwrap();
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            "[acronyms]\nCaP | calcium phosphate\nHA | hydroxyapatite\n"
        );

        db.start_empty().unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), EMPTY_CUSTOM_DICTIONARY);
        assert_eq!(db.snapshot().expand_query("CaP"), vec![term("cap")]);

        db.reset_to_template().unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), SMALL_TEMPLATE);
        assert_eq!(db.snapshot().expand_query("CaP"), cap_expansion());
    }

    #[test]
    fn invalid_replacement_changes_nothing() {
        let (root, registry) = registry("invalid");
        let db_dir = root.join("databases").join("db");
        let db = registry.open_database(&db_dir).unwrap();
        let before = db.snapshot();
        let err = db.replace_text("[roman]\nmin_value = 50\nmax_value = 10\n").unwrap_err();
        assert!(matches!(err, ConfigError::Invalid { .. }), "{err}");
        assert!(db.replace_text("[acronyms]\nHA\n").is_err());
        assert_eq!(fs::read_to_string(db_dir.join(DATABASE_FILE_NAME)).unwrap(), SMALL_TEMPLATE);
        assert!(Arc::ptr_eq(&before, &db.snapshot()));
    }

    #[test]
    fn conflicting_hand_edit_is_detected_then_reloaded() {
        let (root, registry) = registry("conflict");
        let db_dir = root.join("databases").join("db");
        let db = registry.open_database(&db_dir).unwrap();
        let path = db_dir.join(DATABASE_FILE_NAME);

        fs::write(&path, format!("{SMALL_TEMPLATE}PEG | polyethylene glycol\n")).unwrap();
        let err = db
            .edit(|doc| doc.add_group(Section::Acronyms, &["PVP", "polyvinylpyrrolidone"]))
            .unwrap_err();
        assert!(matches!(err, ConfigError::Conflict { .. }));

        db.reload().unwrap();
        assert_eq!(
            db.snapshot().expand_query("PEG"),
            any(vec![exact(&["PEG"]), phrase(&["polyethylene", "glycol"])])
        );
    }

    #[test]
    fn reload_with_bad_file_keeps_live_dictionary_and_deleted_file_is_recopied() {
        let (root, registry) = registry("reload");
        let db_dir = root.join("databases").join("db");
        let db = registry.open_database(&db_dir).unwrap();
        let path = db_dir.join(DATABASE_FILE_NAME);

        fs::write(&path, "[acronyms]\nHA\n").unwrap();
        assert!(db.reload().is_err());
        assert_eq!(db.snapshot().expand_query("CaP"), cap_expansion());

        fs::remove_file(&path).unwrap();
        db.reload().unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), SMALL_TEMPLATE);
    }

    #[test]
    fn restore_builtin_template() {
        let (root, registry) = registry("builtin");
        registry.restore_builtin_template().unwrap();
        assert!(fs::read_to_string(root.join(DEFAULT_FILE_NAME)).unwrap().contains("H2O | water"));
    }
}