[package]
name = "core-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
core-index = { path = "../core-index" }
core-query = { path = "../core-query" }
core-storage = { path = "../core-storage" }
core-core = { path = "../core-core" }

serde = { workspace = true }
serde_json = "1"
tracing = "0.1.44"
thiserror = "2"
toml = "1.1.2"

