[package]
name = "core-runtime"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }

[dependencies]
core-index = { path = "../core-index" }
core-query = { path = "../core-query" }
core-protocol = { path = "../core-protocol" }
core-storage = { path = "../core-storage" }
core-core = { path = "../core-core" }
#core-auth = {path = "../core-auth"}
core-logs ={path ="../core-logs"}
uuid = { version = "1.23.4", features = ["v4"] }
serde = { workspace = true,}
tokio = { workspace = true }
serde_json = { version = "1", features = ["preserve_order"] }
slog ="2"
slog-async="2"
slog-term="2"
slog-envlogger="2"
slog-scope="4"
thiserror = "2"
toml = "1.1.2"
axum = "0.8.9"
reqwest = "0.13.4"
indexmap = { version = "2.14.0", features = ["serde"] }
rayon = "1.12.0"
crossbeam-channel = "0.5.16"
parking_lot = "0.12.5"
