#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Permission {
    //basic
    Search,
    Retrieve,
    Lookup,
    Insert,
    Upsert,
    Delete,
    Status,
    Replace,
    ClearDB,
    GetLogs,
    ClearLogs,
    AllFields,
    //databases
    CreateDatabase,
    DeleteDatabase,
    RenameDatabse,
    ListDatabases,
    StartDB,
    StopDB,
    RestartDB,
    //config/policy
    GetPolicy,
    SetPolicy,
    GetConfig,
    SetConfig,
    Reindex,
    //users
    CreateUser,
    DeleteUser,
    UpdateRole,
    UpdatePwd,
    //backup
    ListBackups,
    Restore,
    Backup,
    BackupFull,
    BackupIncremental,
}

impl Permission {
    pub fn command_str(s: &str) -> Option<Self> {
        match s {
            "Search" => Some(Permission::Search),
            "Retrieve" => Some(Permission::Retrieve),
            "Lookup" => Some(Permission::Lookup),
            "Insert" => Some(Permission::Insert),
            "Upsert" => Some(Permission::Upsert),
            "Delete" => Some(Permission::Delete),
            "Status" => Some(Permission::Status),
            "Replace" => Some(Permission::Replace),
            "ClearDB" => Some(Permission::ClearDB),
            "GetLogs" => Some(Permission::GetLogs),
            "ClearLogs" => Some(Permission::ClearLogs),
            "RenameDatabse" => Some(Permission::RenameDatabse),
            "CreateDatabase" => Some(Permission::CreateDatabase),
            "DeleteDatabase" => Some(Permission::DeleteDatabase),
            "ListDatabases" => Some(Permission::ListDatabases),
            "AllFields" => Some(Permission::AllFields),
            "StartDB" => Some(Permission::StartDB),
            "StopDB" => Some(Permission::StopDB),
            "RestartDB" => Some(Permission::RestartDB),
            "GetPolicy" => Some(Permission::GetPolicy),
            "SetPolicy" => Some(Permission::SetPolicy),
            "GetConfig" => Some(Permission::GetConfig),
            "SetConfig" => Some(Permission::SetConfig),
            "Reindex" => Some(Permission::Reindex),
            "CreateUser" => Some(Permission::CreateUser),
            "DeleteUser" => Some(Permission::DeleteUser),
            "UpdateRole" => Some(Permission::UpdateRole),
            "UpdatePwd" => Some(Permission::UpdatePwd),
            "Restore" => Some(Permission::Restore),
            "BackupFull" => Some(Permission::BackupFull),
            "ListBackups" => Some(Permission::ListBackups),
            "BackupIncremental" => Some(Permission::BackupIncremental),
            _ => None,
        }
    }
}
