[package]
name = "core-query"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
simd-json = "0.18.1"
core-index = { path = "../core-index" }
core-protocol = {path = "../core-protocol"}
core-timing = { path = "../core-timing" }
indexmap = "2.14.2"

[features]
timing = ["core-timing/timing", "core-index/timing"]

[dev-dependencies]
criterion = { workspace = true }
core-testkit = { path = "../core-testkit" }

